import { useState } from 'react';
import { detectBias, rewriteJD } from '../api/bias';
import { AlertTriangle, CheckCircle, FileText, Download, Loader } from 'lucide-react';

export default function BiasDetectionPanel() {
  const [jdText, setJdText] = useState('');
  const [mode, setMode] = useState('detect'); // 'detect' or 'rewrite'
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState(null);
  const [error, setError] = useState('');

  const handleAnalysis = async () => {
    if (!jdText.trim()) {
      setError('Please enter job description text');
      return;
    }

    setLoading(true);
    setError('');
    setResults(null);

    try {
      const userData = {
        user_id: localStorage.getItem('userId') || 'demo-user',
        user_role: localStorage.getItem('role') || 'recruiter'
      };

      if (mode === 'detect') {
        const result = await detectBias({
          jd_text: jdText,
          ...userData
        });
        setResults(result);
      } else {
        const result = await rewriteJD({
          jd_text: jdText,
          target_demographics: ['gender_neutral', 'age_inclusive', 'culturally_diverse'],
          user_id: userData.user_id
        });
        setResults(result);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadCertificate = () => {
    if (results?.certificate) {
      const cert = results.certificate;
      const certText = `
BIAS ANALYSIS CERTIFICATE
========================

Certificate ID: ${cert.id}
Issued Date: ${new Date(cert.issued_date).toLocaleDateString()}
Validity: ${cert.validity}
Compliance Level: ${cert.compliance_level}

This certificate validates that the job description has been analyzed for bias and meets inclusivity standards.

Generated by Merit Mind AI
      `.trim();
      
      const blob = new Blob([certText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `bias_certificate_${cert.id}.txt`;
      a.click();
    }
  };

  return (
    <div style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
      <div className="glass-card" style={{ padding: '32px' }}>
        <div style={{ marginBottom: '24px' }}>
          <h2 style={{ color: 'white', fontSize: '2rem', fontWeight: '800', marginBottom: '8px' }}>
            AI Bias Detection & JD Rewrite
          </h2>
          <p style={{ color: '#B8B8FF', fontSize: '1rem' }}>
            Detect bias in job descriptions and generate inclusive alternatives
          </p>
        </div>

        {/* Mode Selection */}
        <div style={{ marginBottom: '24px' }}>
          <div style={{ display: 'flex', gap: '12px' }}>
            <button
              onClick={() => setMode('detect')}
              style={{
                padding: '12px 24px',
                borderRadius: '8px',
                border: 'none',
                background: mode === 'detect' ? '#7B2FFF' : 'rgba(255, 255, 255, 0.1)',
                color: 'white',
                fontWeight: '600',
                cursor: 'pointer',
                transition: 'all 0.3s ease'
              }}
            >
              <AlertTriangle size={16} style={{ marginRight: '8px', display: 'inline' }} />
              Detect Bias
            </button>
            <button
              onClick={() => setMode('rewrite')}
              style={{
                padding: '12px 24px',
                borderRadius: '8px',
                border: 'none',
                background: mode === 'rewrite' ? '#7B2FFF' : 'rgba(255, 255, 255, 0.1)',
                color: 'white',
                fontWeight: '600',
                cursor: 'pointer',
                transition: 'all 0.3s ease'
              }}
            >
              <FileText size={16} style={{ marginRight: '8px', display: 'inline' }} />
              Rewrite JD
            </button>
          </div>
        </div>

        {/* Input Area */}
        <div style={{ marginBottom: '24px' }}>
          <label style={{ display: 'block', color: 'white', fontWeight: '600', marginBottom: '8px' }}>
            Job Description Text
          </label>
          <textarea
            value={jdText}
            onChange={(e) => setJdText(e.target.value)}
            placeholder={mode === 'detect' 
              ? "Paste your job description here to analyze for potential bias..."
              : "Paste your job description here to generate inclusive alternatives..."
            }
            style={{
              width: '100%',
              minHeight: '200px',
              padding: '16px',
              borderRadius: '8px',
              border: '1px solid rgba(255, 255, 255, 0.2)',
              background: 'rgba(255, 255, 255, 0.05)',
              color: 'white',
              fontSize: '14px',
              resize: 'vertical'
            }}
          />
        </div>

        {/* Action Button */}
        <div style={{ marginBottom: '24px' }}>
          <button
            onClick={handleAnalysis}
            disabled={loading || !jdText.trim()}
            style={{
              padding: '12px 32px',
              borderRadius: '8px',
              border: 'none',
              background: loading || !jdText.trim() ? '#666' : '#7B2FFF',
              color: 'white',
              fontWeight: '600',
              cursor: loading || !jdText.trim() ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            {loading ? (
              <>
                <Loader size={16} style={{ animation: 'spin 1s linear infinite' }} />
                {mode === 'detect' ? 'Analyzing...' : 'Rewriting...'}
              </>
            ) : (
              <>
                {mode === 'detect' ? 'Analyze for Bias' : 'Generate Inclusive JD'}
              </>
            )}
          </button>
        </div>

        {/* Error Display */}
        {error && (
          <div style={{
            padding: '16px',
            borderRadius: '8px',
            background: 'rgba(255, 69, 69, 0.1)',
            border: '1px solid rgba(255, 69, 69, 0.3)',
            color: '#FF4545',
            marginBottom: '24px'
          }}>
            {error}
          </div>
        )}

        {/* Results */}
        {results && (
          <div className="glass-card" style={{ padding: '24px', marginTop: '24px' }}>
            {mode === 'detect' ? (
              // Bias Detection Results
              <div>
                <h3 style={{ color: 'white', fontSize: '1.5rem', fontWeight: '700', marginBottom: '16px' }}>
                  Bias Analysis Results
                </h3>
                
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginBottom: '24px' }}>
                  <div className="glass-card" style={{ padding: '16px', textAlign: 'center' }}>
                    <div style={{ fontSize: '2rem', fontWeight: '800', color: results.overall_bias_score > 0.5 ? '#FF4545' : '#00FF88' }}>
                      {(results.overall_bias_score * 100).toFixed(1)}%
                    </div>
                    <div style={{ color: '#B8B8FF', fontSize: '0.875rem' }}>Overall Bias Score</div>
                  </div>
                  
                  <div className="glass-card" style={{ padding: '16px', textAlign: 'center' }}>
                    <div style={{ fontSize: '2rem', fontWeight: '800', color: '#7B2FFF' }}>
                      {results.bias_indicators?.length || 0}
                    </div>
                    <div style={{ color: '#B8B8FF', fontSize: '0.875rem' }}>Issues Found</div>
                  </div>
                  
                  <div className="glass-card" style={{ padding: '16px', textAlign: 'center' }}>
                    <div style={{ fontSize: '2rem', fontWeight: '800', color: '#FFB800' }}>
                      {(results.confidence_score * 100).toFixed(1)}%
                    </div>
                    <div style={{ color: '#B8B8FF', fontSize: '0.875rem' }}>Confidence</div>
                  </div>
                </div>

                {results.bias_indicators && results.bias_indicators.length > 0 && (
                  <div style={{ marginBottom: '24px' }}>
                    <h4 style={{ color: 'white', fontWeight: '600', marginBottom: '12px' }}>Bias Indicators</h4>
                    {results.bias_indicators.map((indicator, idx) => (
                      <div key={idx} className="glass-card" style={{ padding: '16px', marginBottom: '12px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'between', marginBottom: '8px' }}>
                          <span style={{ color: 'white', fontWeight: '600', textTransform: 'capitalize' }}>
                            {indicator.type.replace('_', ' ')}
                          </span>
                          <span style={{ 
                            padding: '4px 8px', 
                            borderRadius: '4px', 
                            fontSize: '0.75rem',
                            fontWeight: '600',
                            background: indicator.severity === 'high' ? 'rgba(255, 69, 69, 0.2)' : 'rgba(255, 184, 0, 0.2)',
                            color: indicator.severity === 'high' ? '#FF4545' : '#FFB800'
                          }}>
                            {indicator.severity}
                          </span>
                        </div>
                        <p style={{ color: '#B8B8FF', fontSize: '0.875rem', marginBottom: '8px' }}>
                          Problematic text: "{indicator.text}"
                        </p>
                        <p style={{ color: 'white', fontSize: '0.875rem' }}>
                          Suggestion: {indicator.suggestion}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

                {results.recommendations && (
                  <div>
                    <h4 style={{ color: 'white', fontWeight: '600', marginBottom: '12px' }}>Recommendations</h4>
                    {results.recommendations.map((rec, idx) => (
                      <div key={idx} style={{ display: 'flex', alignItems: 'center', marginBottom: '8px' }}>
                        <CheckCircle size={16} style={{ color: '#00FF88', marginRight: '8px' }} />
                        <span style={{ color: '#B8B8FF' }}>{rec}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              // JD Rewrite Results
              <div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'between', marginBottom: '16px' }}>
                  <h3 style={{ color: 'white', fontSize: '1.5rem', fontWeight: '700' }}>
                    Inclusive JD Variants
                  </h3>
                  {results.certificate && (
                    <button
                      onClick={downloadCertificate}
                      style={{
                        padding: '8px 16px',
                        borderRadius: '6px',
                        border: 'none',
                        background: '#00FF88',
                        color: '#0D0B1E',
                        fontWeight: '600',
                        cursor: 'pointer',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '6px'
                      }}
                    >
                      <Download size={14} />
                      Certificate
                    </button>
                  )}
                </div>

                <div style={{ marginBottom: '24px' }}>
                  <div className="glass-card" style={{ padding: '16px', textAlign: 'center' }}>
                    <div style={{ fontSize: '2rem', fontWeight: '800', color: '#00FF88' }}>
                      {(results.overall_improvement * 100).toFixed(1)}%
                    </div>
                    <div style={{ color: '#B8B8FF', fontSize: '0.875rem' }}>Overall bias reduction</div>
                  </div>
                </div>

                {results.variants && results.variants.map((variant, idx) => (
                  <div key={idx} className="glass-card" style={{ padding: '20px', marginBottom: '16px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'between', marginBottom: '12px' }}>
                      <h4 style={{ color: 'white', fontWeight: '600' }}>{variant.title}</h4>
                      <div style={{ display: 'flex', gap: '12px' }}>
                        <div style={{ textAlign: 'center' }}>
                          <div style={{ fontSize: '1.25rem', fontWeight: '700', color: '#00FF88' }}>
                            {(variant.bias_reduction * 100).toFixed(0)}%
                          </div>
                          <div style={{ fontSize: '0.75rem', color: '#B8B8FF' }}>Bias Reduction</div>
                        </div>
                        <div style={{ textAlign: 'center' }}>
                          <div style={{ fontSize: '1.25rem', fontWeight: '700', color: '#7B2FFF' }}>
                            {(variant.inclusivity_score * 100).toFixed(0)}%
                          </div>
                          <div style={{ fontSize: '0.75rem', color: '#B8B8FF' }}>Inclusivity</div>
                        </div>
                      </div>
                    </div>
                    
                    <div style={{
                      padding: '16px',
                      borderRadius: '6px',
                      background: 'rgba(255, 255, 255, 0.05)',
                      border: '1px solid rgba(255, 255, 255, 0.1)',
                      marginBottom: '12px',
                      fontFamily: 'monospace',
                      color: '#E8E8E8',
                      lineHeight: '1.5'
                    }}>
                      {variant.text}
                    </div>

                    <div>
                      <p style={{ color: '#B8B8FF', fontWeight: '600', marginBottom: '6px' }}>Changes made:</p>
                      {variant.changes_made.map((change, changeIdx) => (
                        <div key={changeIdx} style={{ display: 'flex', alignItems: 'center', marginBottom: '4px' }}>
                          <CheckCircle size={14} style={{ color: '#00FF88', marginRight: '8px' }} />
                          <span style={{ color: '#B8B8FF', fontSize: '0.875rem' }}>{change}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}