export default function AuditCertificate({ certificate }) {
  if (!certificate) {
    return null;
  }

  const handleDownloadCertificate = () => {
    // Generate a simple HTML certificate
    const certificateHTML = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Merit Mind Bias Audit Certificate</title>
        <style>
          body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            background: #f9f9f9;
          }
          .certificate {
            background: white;
            border: 3px solid #7C3AED;
            borderRadius: 12px;
            padding: 40px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
          }
          .logo {
            font-size: 2em;
            font-weight: bold;
            background: linear-gradient(135deg, #7C3AED, #EC4899);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
          }
          .title {
            font-size: 1.5em;
            color: #1F1235;
            margin: 10px 0;
          }
          .field-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin: 20px 0;
          }
          .field {
            padding: 10px;
            border-bottom: 1px solid #e5e7eb;
          }
          .field-label {
            font-size: 0.8em;
            text-transform: uppercase;
            color: #9ca3af;
            font-weight: 600;
            margin-bottom: 5px;
          }
          .field-value {
            font-weight: 600;
            color: #1f2937;
          }
          .compliance-badges {
            display: flex;
            gap: 8px;
            flex-wrap: wrap;
          }
          .badge {
            background: #f3f4f6;
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 0.8em;
            color: #374151;
          }
          .footer {
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
            margin-top: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 0.9em;
          }
        </style>
      </head>
      <body>
        <div class="certificate">
          <div class="header">
            <div class="logo">Merit Mind</div>
            <h1 class="title">Bias Audit Certificate</h1>
            <p>This certifies that the job description has been analyzed for bias and rewritten for inclusive recruitment</p>
          </div>
          
          <div class="field-grid">
            <div class="field">
              <div class="field-label">Original Bias Score</div>
              <div class="field-value">${certificate.original_bias_score}/100</div>
            </div>
            <div class="field">
              <div class="field-label">Rewritten Bias Score</div>
              <div class="field-value">${certificate.rewritten_bias_score}/100</div>
            </div>
            <div class="field">
              <div class="field-label">Intersections Resolved</div>
              <div class="field-value">${certificate.intersections_resolved}</div>
            </div>
            <div class="field">
              <div class="field-label">Certified By</div>
              <div class="field-value">${certificate.certified_by}</div>
            </div>
            <div class="field">
              <div class="field-label">Date</div>
              <div class="field-value">${certificate.date}</div>
            </div>
            <div class="field">
              <div class="field-label">Compliant With</div>
              <div class="field-value compliance-badges">
                ${certificate.compliant_with?.map(item => `<span class="badge">${item}</span>`).join('')}
              </div>
            </div>
          </div>
          
          <div class="footer">
            <p>Generated by Merit Mind AI-Powered Bias Detection System</p>
            <p>This certificate validates that the analyzed content meets fairness and inclusion standards for Indian recruitment practices.</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Create and trigger download
    const blob = new Blob([certificateHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'MeritMind_Audit_Certificate.html';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{
      backgroundColor: 'white',
      border: '1px solid #E5E7EB',
      borderRadius: '12px',
      boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
      overflow: 'hidden'
    }}>
      <div style={{
        background: '#FAF5FF',
        borderBottom: '1px solid #DDD6FE',
        padding: '16px 24px'
      }}>
        <h3 style={{
          fontSize: '16px',
          fontWeight: '600',
          color: '#1F1235',
          fontFamily: "'Poppins', sans-serif",
          margin: 0
        }}>
          Bias Audit Certificate
        </h3>
      </div>
      
      <div style={{
        padding: '24px',
        background: '#FAF5FF',
        borderBottom: '1px solid #DDD6FE'
      }}>
        {/* Certificate Fields - Two Column Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '12px' }}>
          <div>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Original Bias Score
            </p>
            <p style={{
              fontSize: '14px',
              fontWeight: '600',
              color: '#1F1235',
              fontFamily: "'Poppins', sans-serif",
              margin: 0
            }}>
              {certificate.original_bias_score}/100
            </p>
          </div>
          
          <div>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Rewritten Bias Score
            </p>
            <p style={{
              fontSize: '14px',
              fontWeight: '600',
              color: '#1F1235',
              fontFamily: "'Poppins', sans-serif",
              margin: 0
            }}>
              {certificate.rewritten_bias_score}/100
            </p>
          </div>
          
          <div>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Intersections Resolved
            </p>
            <p style={{
              fontSize: '14px',
              fontWeight: '600',
              color: '#1F1235',
              fontFamily: "'Poppins', sans-serif",
              margin: 0
            }}>
              {certificate.intersections_resolved}
            </p>
          </div>
          
          <div>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Date
            </p>
            <p style={{
              fontSize: '14px',
              fontWeight: '600',
              color: '#1F1235',
              fontFamily: "'Poppins', sans-serif",
              margin: 0
            }}>
              {certificate.date}
            </p>
          </div>
          
          <div style={{ gridColumn: 'span 2' }}>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Compliant With
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>
              {certificate.compliant_with?.map((item, index) => (
                <span 
                  key={index}
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    padding: '4px 8px',
                    borderRadius: '999px',
                    fontSize: '11px',
                    fontWeight: '500',
                    fontFamily: "'Poppins', sans-serif",
                    background: '#DDD6FE',
                    color: '#7C3AED'
                  }}
                >
                  {item}
                </span>
              ))}
            </div>
          </div>
          
          <div style={{ gridColumn: 'span 2' }}>
            <p style={{
              fontSize: '11px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              color: '#9CA3AF',
              fontFamily: "'Poppins', sans-serif",
              marginBottom: '4px'
            }}>
              Certified By
            </p>
            <p style={{
              fontSize: '14px',
              fontWeight: '600',
              color: '#1F1235',
              fontFamily: "'Poppins', sans-serif",
              margin: 0
            }}>
              {certificate.certified_by}
            </p>
          </div>
        </div>
      </div>
      
      {/* Action Row */}
      <div style={{ padding: '16px 24px', background: 'white' }}>
        <button
          onClick={handleDownloadCertificate}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            padding: '10px 16px',
            border: '1px solid #7C3AED',
            fontSize: '13px',
            fontWeight: '500',
            fontFamily: "'Poppins', sans-serif",
            borderRadius: '8px',
            color: '#7C3AED',
            background: 'transparent',
            cursor: 'pointer',
            transition: 'all 0.2s ease'
          }}
          onMouseEnter={(e) => e.target.style.background = '#FAF5FF'}
          onMouseLeave={(e) => e.target.style.background = 'transparent'}
        >
          <svg style={{ width: '16px', height: '16px', marginRight: '8px' }} fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Certificate
        </button>
      </div>
    </div>
  );
}
